Controllers/AdminController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Website.Data;
using Website.Models;

namespace Website.Controllers
{
    public class AdminController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly ApplicationDbContext _context;

        public AdminController(SignInManager<IdentityUser> signInManager,
            UserManager<IdentityUser> userManager,
            ApplicationDbContext context)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Login()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            // Clear the existing external cookie to ensure a clean login process
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login([Bind("Email,Password,RememberMe")] InputLoginModel input, string returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");

            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(input.Email, input.Password, input.RememberMe, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    return LocalRedirect(returnUrl);
                }
                if (result.IsLockedOut)
                {
                    return RedirectToPage("./Lockout");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return View();
                }
            }

            // If we got this far, something failed, redisplay form
            return View();
        }

        [HttpGet]
        [Authorize]
        public IActionResult UserList() => View(_userManager.Users.ToList());

        [HttpGet]
        [Authorize(Roles ="admin")]
        public async Task<IActionResult> ChangePasswordAsync(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{userId}'.");
            }

            InputChangePasswordModel model = new InputChangePasswordModel
            {
                Email = user.Email
            };

            return View(model);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Logout(string returnUrl = null)
        {
            await _signInManager.SignOutAsync();
            if (returnUrl != null)
            {
                return LocalRedirect(returnUrl);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }


        [HttpPost]
        [Authorize(Roles ="admin")]
        public async Task<IActionResult> ChangePassword(InputChangePasswordModel input)
        {
            var user = await _userManager.FindByEmailAsync(input.Email);
            if (user == null)
            {
                return RedirectToPage("./ResetPasswordConfirmation");
            }
            var result = await _userManager.ChangePasswordAsync(user, input.Password, input.Password);
            if (result.Succeeded)
            {
                return RedirectToPage("./ResetPasswordConfirmation");
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ForgotPassword(string email)
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(email);
                if (user == null || !(await _userManager.IsEmailConfirmedAsync(user)))
                {
                    return RedirectToAction("Index", "Home");
                }

                var code = await _userManager.GeneratePasswordResetTokenAsync(user);
                code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
                var callbackUrl = Url.Page(
                    "/Account/ResetPassword",
                    pageHandler: null,
                    values: new { area = "Identity", code },
                    protocol: Request.Scheme);



                return RedirectToAction("Index", "Home");
            }

            return RedirectToAction(nameof(Login));
        }

        [Authorize(Roles = "admin")]
        public IActionResult Create()=> View();

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> ContactMeResponses()
        {
            var contactModels = await _context.ContactModel.ToListAsync();
            if (contactModels == null)
            {
                return NotFound();
            }

            return View(contactModels);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create(InputChangePasswordModel input)
        {
            if (ModelState.IsValid)
            {
                var user = new IdentityUser { UserName = input.Email, Email = input.Email };
                var result = await _userManager.CreateAsync(user, input.Password);
                if (result.Succeeded)
                {
                    return Redirect(nameof(UserList));
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            return View();
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{userId}'.");
            }

            var result = await _userManager.DeleteAsync(user);
            var userIdGot = await _userManager.GetUserIdAsync(user);
            if (!result.Succeeded)
            {
                throw new InvalidOperationException($"Unexpected error occurred deleting user with ID '{userIdGot}'.");
            }
            return Redirect(nameof(UserList));
        }
    }
}

Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;
using Website.Core;
using Website.Data;
using Website.Models;
using Website.Models.ViewModels;

namespace Website.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProjectsController(ApplicationDbContext context)
        {
            _context = context;
        }


        public async Task<IActionResult> All()
        {
            var projectModels = await _context.ProjectModel.ToListAsync();
            if (projectModels == null)
            {
                return NotFound();
            }

            return View(projectModels);
        }

        public async Task<IActionResult> Filter([FromQuery]string language)
        {
            var projectModels = await _context.ProjectModel.Where(p => p.LanguageTag == language).ToListAsync();
            if (projectModels == null)
            {
                return NotFound();
            }

            return View(projectModels);
        }

        public IActionResult Featured() => View();

        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _context.ProjectModel.ToListAsync());
        }

        [Authorize(Roles = "admin")]
        public async Task<RedirectToActionResult> GitGet()
        {
            GitSync gitSync = new GitSync();
            var projects = await gitSync.GetProjects();

            foreach (var project in projects)
            {
                if(!_context.ProjectModel.Any(p => p.Name == project.Name))
                {
                    _context.ProjectModel.Add(project);
                }
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "admin")]
        public async Task<RedirectToActionResult> GitGetAndUpdate()
        {
            GitSync gitSync = new GitSync();
            var projects = await gitSync.GetProjects();

            foreach (var project in projects)
            {
                var dbProject = await _context.ProjectModel.SingleOrDefaultAsync(p => p.Name == project.Name);
                if (dbProject == null)
                {
                    _context.ProjectModel.Add(project);
                }
                else
                {
                    //BAD
                    dbProject.LanguageTag = project.LanguageTag;
                    dbProject.ImageLink = project.ImageLink;
                    dbProject.Description = project.Description;
                    dbProject.DescriptionShort = project.DescriptionShort;
                    //BAD
                }
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Project(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projectModel = await _context.ProjectModel
                .SingleOrDefaultAsync(m => m.Id == id);
            if (projectModel == null)
            {
                return NotFound();
            }
            var viewModel = new ProjectViewModel(projectModel);

            var rand = new Random();
            int maxValue = _context.ProjectModel.Count();
            int randId = 0;
            
            for (int i = 0; i < 4; i++)
            {
                ProjectModel gotProject;
                do
                {
                    randId = rand.Next(maxValue);
                } while (id == randId || viewModel.OtherProjects.ContainsKey(randId));

                gotProject = await _context.ProjectModel.SingleOrDefaultAsync(m => m.Id == randId);
                if (gotProject != null)
                    viewModel.OtherProjects.Add(randId, gotProject.ImageLink);
                else
                    i--;      //BAD          
            }

            return View(viewModel);
        }

        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projectModel = await _context.ProjectModel.SingleOrDefaultAsync(m => m.Id == id);
            if (projectModel == null)
            {
                return NotFound();
            }

            return View(projectModel);
        }

        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,DescriptionShort,Description,LanguageTag,ImageLink,GithubLink")] ProjectModel projectModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(projectModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(projectModel);
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projectModel = await _context.ProjectModel.FindAsync(id);
            if (projectModel == null)
            {
                return NotFound();
            }
            return View(projectModel);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,DescriptionShort,Description,LanguageTag,ImageLink,GithubLink")] ProjectModel projectModel)
        {
            if (id != projectModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(projectModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectModelExists(projectModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(projectModel);
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projectModel = await _context.ProjectModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (projectModel == null)
            {
                return NotFound();
            }

            return View(projectModel);
        }

        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var projectModel = await _context.ProjectModel.FindAsync(id);
            _context.ProjectModel.Remove(projectModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProjectModelExists(int id)
        {
            return _context.ProjectModel.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>@ViewData["Title"] - Website</title>

    <link rel="icon" href="/assets/img/47089207.ico">

    <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:300,400,700">
    <link rel="stylesheet" href="/assets/fonts/ionicons.min.css">
    <link rel="stylesheet" href="/assets/css/Highlight-Blue.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.1.1/aos.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/css/pikaday.min.css">
    <link rel="stylesheet" href="/assets/css/Projects-Horizontal.css">

</head>
<body>
    <nav class="navbar navbar-dark navbar-expand-lg fixed-top bg-white portfolio-navbar gradient">
        <div class="container">
            <a class="navbar-brand logo" asp-controller="Home" asp-action="Index">D3AD</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navbarNav"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse"
                 id="navbarNav">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item" role="presentation"><a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" asp-area="" asp-controller="Projects" asp-action="Featured">Projects</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Cv">CV</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" asp-area="" asp-controller="Home" asp-action="ContactMe">Contact me</a></li>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item" role="presentation"><a class="nav-link" asp-area="" asp-controller="Admin" asp-action="UserList">Manage</a></li>
                        <li class="nav-item" role="presentation"><a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Logout">@User.Identity.Name</a></li>
                    }
                    else
                    {
                        <li class="nav-item" role="presentation"><a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Login">Login</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    @RenderBody()
    <footer class="page-footer">
        <div class="container">
            <div class="social-icons">
                <a href="https://www.facebook.com/YevheniiG" target="_blank" rel="noopener noreferrer"><i class="icon ion-social-facebook"></i></a>
                <a href="https://www.instagram.com/evg.gordi/" target="_blank" rel="noopener noreferrer"><i class="icon ion-social-instagram-outline"></i></a>
                <a href="https://github.com/D3AD-E" target="_blank" rel="noopener noreferrer"><i class="icon ion-social-github"></i></a>
            </div>
        </div>
    </footer>
    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="/assets/js/bs-init.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.1.1/aos.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/pikaday.min.js"></script>
    <script src="/assets/js/theme.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>